config/routes.rb
ControlCredito::Application.routes.draw do

  resources :quotes

  resources :sales

  resources :people

  get '/json/sales', to: 'sales#index_json', as: 'index_json_sale'

  get '/json/sale/:id', to: 'sales#show_json', as: 'show_json_sale'
  
  post '/json/pay/:id', to: 'quotes#pay', as: 'pay_json_quote'

  post '/json/update_amount/:id', to: 'quotes#update_amount', as: 'update_amount_json_quote'

  get '/sales/delete/:id', to: 'sales#delete', as: 'delete_sale'

  get '/people/delete/:id', to: 'people#delete', as: 'delete_person'

  get '/sales/quotes/:sale_id', to: 'quotes#quotes_sale', as: 'quotes_sale'

  post '/sales/quotes/pay/:id', to: 'quotes#pay', as: 'pay_quote'

  root 'static_pages#home'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

#  get '/signup' => 'users#new'
#  post '/users' => 'users#create'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :sale
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :pay, :update_amount]
  skip_before_filter :verify_authenticity_token
  before_filter :authorize, except: [:pay,:update_amount]
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  def quotes_sale

    @sale = Sale.find(params[:sale_id])

    @quotes = Quote.where(sale_id:  @sale.id).order(:number)

  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  def pay
     @quote.is_paid = true
     @quote.save
     respond_to do |format|
       format.json {render json: {:status => "200"}}
     end
  end
  def update_amount
    puts '---------------------------'
    puts params[:amount]
    puts '---------------------------'
    @quote.amount = params[:amount]
    @quote.save!
    respond_to do |format|
      format.json {render json: {:status => "200"}}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:number, :total, :mounth, :year, :is_paid, :amount)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div>
  <div class="field">
    <%= f.label :mounth %><br>
    <%= f.number_field :mounth %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :is_paid %><br>
    <%= f.check_box :is_paid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Total</th>
      <th>Mounth</th>
      <th>Year</th>
      <th>Is paid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.number %></td>
        <td><%= quote.total %></td>
        <td><%= quote.mounth %></td>
        <td><%= quote.year %></td>
        <td><%= quote.is_paid %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/quotes_sale.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">View Quotes</h1>
  <h1 style="text-align: center"><small>&laquo<%= @sale.description.capitalize %>&raquo</small></h1>
</div>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" style="text-align: center">
  <thead>
    <tr>
      <th style="width:10%; text-align: center">#</th>
      <th style="text-align: center;width:30%">Amount</th>
      <th style="text-align: center;width:30%">Month</th>
      <th style="text-align: center; width: 30%">Is paid</th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.number < 10? '0' + quote.number.to_s : quote.number %>/<%= quote.total < 10? '0' + quote.total.to_s : quote.total %></td>
        <td>$ <%= '%.2f' % quote.amount %></td>
        <% if quote.mounth < 10 %>
            <td>0<%= quote.mounth %>/<%= quote.year %></td>
        <% else %>
            <td><%= quote.mounth %>/<%= quote.year %></td>
        <% end %>

        <% if quote.is_paid %>
            <td>Paid</td>
        <% else %>
            <td><a id="quote_<%= quote.id %>_pay" class="pay" style="cursor: pointer" data-toggle="modal" data-target="#confirmPay" data-quote="<%= quote.id %>" data-number="<%= quote.number < 10? '0' + quote.number.to_s : quote.number %>/<%= quote.total < 10? '0' + quote.total.to_s : quote.total %>" >Pay Quote</a></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<div class="col-sm-2">
    <%= link_to 'Back', @sale, :class => 'btn btn-default btn-block'  %>
</div>


<!-- Modal -->
<div class="modal fade" id="confirmPay" tabindex="-1" role="dialog" aria-labelledby="confirmPay">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmation</h4>
      </div>
      <div class="modal-body">
        <p id="message_modal_confirmPay">Are you sure want to pay the quote number X?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-loading-text="Loading..." id="pay_button" >Pay Quote</button>
      </div>
    </div>
  </div>
</div>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @quote.number %>
</p>

<p>
  <strong>Total:</strong>
  <%= @quote.total %>
</p>

<p>
  <strong>Mounth:</strong>
  <%= @quote.mounth %>
</p>

<p>
  <strong>Year:</strong>
  <%= @quote.year %>
</p>

<p>
  <strong>Is pais:</strong>
  <%= @quote.is_paid %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @quote.amount %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>