config/routes.rb
ControlCredito::Application.routes.draw do

  resources :quotes

  resources :sales

  resources :people

  get '/json/sales', to: 'sales#index_json', as: 'index_json_sale'

  get '/json/sale/:id', to: 'sales#show_json', as: 'show_json_sale'
  
  post '/json/pay/:id', to: 'quotes#pay', as: 'pay_json_quote'

  post '/json/update_amount/:id', to: 'quotes#update_amount', as: 'update_amount_json_quote'

  get '/sales/delete/:id', to: 'sales#delete', as: 'delete_sale'

  get '/people/delete/:id', to: 'people#delete', as: 'delete_person'

  get '/sales/quotes/:sale_id', to: 'quotes#quotes_sale', as: 'quotes_sale'

  post '/sales/quotes/pay/:id', to: 'quotes#pay', as: 'pay_quote'

  root 'static_pages#home'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

#  get '/signup' => 'users#new'
#  post '/users' => 'users#create'

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, :presence => true
  validates :name, :uniqueness => true
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :delete]
  before_filter :authorize

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def delete

    @sales = Sale.where(:person_id => @person.id)
    if @sales.size > 0
      message = "The person: \"#{@person.name.to_s.capitalize } \" was not delete because has sales."
      respond_to do |format|
        format.html { redirect_to people_url, alert: message }
        format.json { head :no_content }
      end
    else
      @person.destroy
      respond_to do |format|
        format.html { redirect_to people_url, notice: "The person: \"#{@person.name.to_s.capitalize } \" was successfully deleted." }
        format.json { head :no_content }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="row" style="background: #eee; border-radius: 5px; padding-top: 20px; padding-bottom: 10px; margin-bottom: 20px;">
  <div class="col-md-1"></div>
  <div class="col-md-10">
        <%= form_for(@person, :html => {:class => 'form-horizontal'})  do |f| %>
        <% if @person.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <p>Problem to save.</p>
            </div>
        <% end %>

        <% if @person.errors[:name].to_a.size > 0 %>
            <div class="form-group has-error">
        <% else %>
            <div class="form-group">
        <% end %>
            <%= f.label :name, class:'col-sm-1 control-label' %>
            <div class="col-sm-6">
                <%= f.text_field :name, class:'form-control'%>
                  <% if @person.errors[:name].to_a.size > 0 %>
                      <p style="color: #a94442"><%= @person.errors[:name].to_a.at(0).to_s.capitalize! %></p>
                  <% end %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 col-xs-6 ">
              <%= f.submit 'Submit', :class => 'btn btn-block btn-success' %>
            </div>
            <div class="col-sm-2 col-xs-6">
              <%= link_to 'Back', people_path, :class => 'btn btn-default btn-block'  %>
            </div>
          </div>

        <% end %>
    </div>
</div>

app/views/people/edit.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">Edit Person</h1>
</div>

<%= render 'form' %>

app/views/people/index.html.erb
<div class="jumbotron">
    <h1 style="text-align: center">Listing People</h1>
</div>
<% if @people.size > 0 %>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th style="width: 60%;">Name</th>
      <th>Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td style="width: 60%;"><%= person.name.to_s.capitalize %></td>
        <td>
            <%= link_to 'Show', person, :class => 'btn btn-info'  %>
            <%= link_to 'View Sales', sales_path(:filter_payment => 'all', :filter_person => person.id), :class => 'btn btn-info'  %>
            <%= link_to 'Edit', edit_person_path(person), :class => 'btn btn-primary'  %>
          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal_<%=person.id%>">Delete</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
    <div class="well well-sm">Not result found.</div>
<% end %>
<br>

<div class="col-sm-2">
<%= link_to 'New Person', new_person_path, :class => 'btn btn-success btn-block' %>
</div>

<% @people.each do |p| %>
    <div class="modal fade" id="deleteModal_<%= p.id %>" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Confirmation</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure to delete the person: "<%= p.name.to_s.capitalize %>"?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= link_to 'Delete', delete_person_path(p), :class => 'btn btn-danger'  %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/people/new.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">New Person</h1>
</div>

<%= render 'form' %>

app/views/people/show.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">View Person</h1>
</div>

<ul class="list-group">
  <li class="list-group-item">
    <p class="col-sm-2 col-xs-12" style="text-align: right"><strong>Name:</strong></p>
      <h5><%= @person.name %></h5>
  </li>
</ul>

<div class="col-sm-2 col-xs-12"><%= link_to 'Back', people_path, :class => 'btn btn-default btn-block' %></div>
<div class="col-sm-2 col-xs-12"><%= link_to 'View Sales', sales_path(:filter_payment => 'all', :filter_person => @person.id), :class => 'btn btn-info btn-block' %></div>
<div class="col-sm-2 col-xs-12"><%= link_to 'Edit', edit_person_path(@person), :class => 'btn btn-primary btn-block' %></div>