config/routes.rb
ControlCredito::Application.routes.draw do

  resources :quotes

  resources :sales

  resources :people

  get '/json/sales', to: 'sales#index_json', as: 'index_json_sale'

  get '/json/sale/:id', to: 'sales#show_json', as: 'show_json_sale'
  
  post '/json/pay/:id', to: 'quotes#pay', as: 'pay_json_quote'

  post '/json/update_amount/:id', to: 'quotes#update_amount', as: 'update_amount_json_quote'

  get '/sales/delete/:id', to: 'sales#delete', as: 'delete_sale'

  get '/people/delete/:id', to: 'people#delete', as: 'delete_person'

  get '/sales/quotes/:sale_id', to: 'quotes#quotes_sale', as: 'quotes_sale'

  post '/sales/quotes/pay/:id', to: 'quotes#pay', as: 'pay_quote'

  root 'static_pages#home'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

#  get '/signup' => 'users#new'
#  post '/users' => 'users#create'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :person
  validates :person_id, :presence => true
  validates :date, :presence => true
  validates :description, :presence => true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :show_json, :edit, :update, :delete]
  before_filter :authorize, except: [:index_json,:show_json]

  # GET /sales
  # GET /sales.json
  def index_json
    @people = Person.where(id:(Sale.where(id:(Quote.where(:is_paid => false).select(:sale_id))).select(:person_id)))
  end

  def index
    @people = Person.all
    if params[:filter_person].nil?
      @sales = Sale.all
    else
      if params[:filter_payment] == 'paid'
        if params[:filter_person] == 'all'
          @sales = Sale.where.not(id:(Quote.where(is_paid: false ).select('sale_id')))
        else
          @sales = Sale.where.not(id:(Quote.where(is_paid: false ).select('sale_id'))).where(:person_id => params[:filter_person])
        end
      else
        if params[:filter_payment] == 'not_paid'
          if params[:filter_person] == 'all'
            @sales = Sale.where(id: (Quote.where(is_paid: false ).select('sale_id')))
          else
            @sales = Sale.where(id: (Quote.where(is_paid: false ).select('sale_id')),:person_id => params[:filter_person])
          end
        else
          if params[:filter_person] != 'all'
            @sales = Sale.where(:person_id => params[:filter_person])
          else
            @sales = Sale.all
          end

        end
      end
    end

  end

  # GET /sales/1
  # GET /sales/1.json
  def show_json
  end

  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    respond_to do |format|
      if @sale.save
        quantity = params[:quotes_quantity].gsub(/[^\d^\.]/, '').to_i

        for i in 1..quantity
          @quote = Quote.new
          @quote.amount = (params[:amount]).gsub(/[^\d^\.]/, '').to_f
          @quote.is_paid = false
          @quote.number = i
          @quote.total = quantity
          @quote.mounth = (@sale.date + i.month).month
          @quote.year = (@sale.date + i.month).year
          @quote.sale = @sale
          @quote.save
        end

        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    quotes = Quote.where(:sale_id =>  @sale.id)

    quotes.each { |q| q.destroy }

    respond_to do |format|
      if @sale.update(sale_params)
        quantity = params[:quotes_quantity].gsub(/[^\d^\.]/, '').to_i

        for i in 1..quantity
          @quote = Quote.new
          @quote.amount = (params[:amount]).gsub(/[^\d^\.]/, '').to_f
          @quote.is_paid = false
          @quote.number = i
          @quote.total = quantity
          @quote.mounth = (@sale.date + i.month).month
          @quote.year = (@sale.date + i.month).year
          @quote.sale = @sale
          @quote.save
        end
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def delete
    @sale.destroy
    quotes = Quote.where(sale_id:  @sale.id)

    quotes.each { |q| q.destroy }
    message = "The sale: \"#{@sale.description.to_s.capitalize } \" was successfully deleted."
    respond_to do |format|
      format.html { redirect_to sales_url, notice: message }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sale
    @sale = Sale.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sale_params
    params.require(:sale).permit(:person_id, :date, :description)
  end

  def quotes_params
    params.permit(:person_id, :date, :description)
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<div class="rowd" style="background: #eee; border-radius: 5px; padding: 20px; margin-bottom: 20px;height: 100%;">
    <%= form_for(@sale, :html => {:class => 'form-horizontal'}) do |f| %>
      <% if @sale.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>Problem to save.</p>
        </div>
      <% end %>
        <% if @sale.errors[:description].to_a.size > 0 %>
            <div class="form-group has-error">
        <% else %>
            <div class="form-group">
        <% end %>

        <%= f.label :description, class:'col-sm-2 control-label' %>

            <div class="col-sm-6">
                <%= f.text_field :description , class:'form-control'%>
                <% if @sale.errors[:description].to_a.size > 0 %>
                    <p style="color: #a94442"><%= @sale.errors[:date].to_a.at(0).to_s.capitalize! %></p>
                <% end %>
                </div>
            </div>

        <% if @sale.errors[:person_id].to_a.size > 0 %>
            <div class="form-group has-error">
        <% else %>
            <div class="form-group">
        <% end %>
            <%= f.label :person_id, class:'col-sm-2 control-label' %>
          <div class="col-sm-6">
            <%= f.collection_select :person_id, Person.all, :id, :name, {prompt: ' - Select a Person - '}, {class: 'form-control'} %>
                <% if @sale.errors[:person_id].to_a.size > 0 %>
                    <p style="color: #a94442"><%= @sale.errors[:person_id].to_a.at(0).to_s.capitalize! %></p>
                <% end %>
          </div>
        </div>
        <% if @sale.errors[:date].to_a.size > 0 %>
            <div class="form-group has-error">
        <% else %>
            <div class="form-group">
        <% end %>

            <%= f.label :date, class:'col-sm-2 control-label' %>

            <div class="col-sm-6">
              <div class="input-group">
                    <%= f.text_field :date , class:'form-control datepicker', style:'background: white; cursor: pointer', readonly: true %>
                    <div class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></div>
              </div>
                  <% if @sale.errors[:date].to_a.size > 0 %>
                      <p style="color: #a94442"><%= @sale.errors[:date].to_a.at(0).to_s.capitalize! %></p>
                  <% end %>
            </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label" for="quotes_quantity">Quantity of Quotes:</label>
          <div class="col-sm-6">
            <input type="number" class="form-control numberinput" id="quotes_quantity" value="1" name="quotes_quantity" min="1" step="1" pattern="\d*" required="true">
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label" for="amount">Amount per Quote:</label>
          <div class="col-sm-6">
            <div class="input-group">
                <div class="input-group-addon">$</div>
                    <input type="number" class="form-control numberinput" id="amount" name="amount" value="1" min="0.01" step="0.01" pattern="\d*" required="true">
                </div>
          </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Confirmation</h4>
              </div>
              <div class="modal-body">
                <p>Are you sure want to save this sale?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <%= f.submit 'Confirm', :class => 'btn btn-success' %>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

        <div class="form-group">
          <div class="col-sm-2"></div>
          <div class="col-sm-2 col-xs-6">
            <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal">Submit</button>
          </div>
          <div class="col-sm-2 col-xs-6">
            <%= link_to 'Back', sales_path, :class => 'btn btn-default btn-block'  %>
          </div>
        </div>
    <% end %>
</div>

app/views/sales/edit.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">Edit Sale</h1>
</div>

<%= render 'form' %>

app/views/sales/index.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">Listing Sales</h1>
</div>

<% if @sales.size > 0 %>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">
      <div class="panel panel-primary">
        <div class="panel-heading" role="tab" id="headingOne">
          <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              Filters
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
          <div class="panel-body">
            <form class="form-inline">
              <div class="form-group" style="margin-right: 10px;">
                <label>Status Payment: </label>
                <select id="filter_payment" class="form-control" style="width: 200px">
                  <option value="all" selected>All</option>
                  <option value="paid" >Only Paid</option>
                  <option value="not_paid">Only not Paid</option>
                </select>
              </div>
              <div class="form-group">
                <label>Person: </label>
                <select id="filter_person" class="form-control" style="width: 200px">
                  <option value="all" selected>All</option>
                  <% @people.each do |p| %>
                      <option value="<%= p.id %>"><%= p.name.to_s.capitalize %></option>
                  <% end %>
                </select>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
          <thead>
            <tr>
              <th style="width: 20%;">Description</th>
              <th style="width: 20%;">People</th>
              <th style="width: 20%;">Date</th>
              <th style="width: 20%;">Paid</th>
              <th style="width: 20%;">Operations</th>
            </tr>
          </thead>

          <tbody>
            <% @sales.each do |sale| %>
              <tr>
                <td><%= sale.description.to_s.capitalize%></td>
                <td><%= sale.person.name.to_s.capitalize%></td>
                <td><%= sale.date.strftime("%d/%m/%Y")  %></td>
                <% porPagar = Quote.where(sale_id:  sale.id, is_paid: false).order(:number) %>
                <% if porPagar.size > 0 %>
                    <td> Quote paid: <%= porPagar.to_a.at(0).number < 11? '0' + (porPagar.to_a.at(0).number - 1 ).to_s : porPagar.to_a.at(0).number - 1  %>/<%= porPagar.to_a.at(0).total < 10? '0' + porPagar.to_a.at(0).total.to_s : porPagar.to_a.at(0).total %> </td>
                <% else %>
                    <td> Paid </td>
                <% end %>

                <td>
                  <%= link_to 'Show', sale, :class => 'btn btn-info'  %>
                  <%= link_to 'Edit', edit_sale_path(sale) , :class => 'btn btn-primary'  %>
                  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal_<%=sale.id%>">Delete</button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
<% else %>
    <div class="well well-sm">Not result found.</div>
<% end %>

<div class="col-sm-2 col-md-3">
    <%= link_to 'New Sale', new_sale_path, :class => 'btn btn-success btn-block' %>
</div>
<% @sales.each do |sale| %>
<div class="modal fade" id="deleteModal_<%= sale.id %>" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirmation</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure to delete the sale: "<%= sale.description.to_s.capitalize %>"?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to 'Delete', delete_sale_path(sale), :class => 'btn btn-danger'  %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/sales/new.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">New Sale</h1>
</div>
<%= render 'form' %>

app/views/sales/show.html.erb
<div class="jumbotron">
  <h1 style="text-align: center">View Sale</h1>
  <h1 style="text-align: center"><small>&laquo<%= @sale.description.capitalize %>&raquo</small></h1>
</div>

<ul class="list-group">
  <li class="list-group-item">
    <p class="col-sm-2 col-xs-12" style="text-align: right"><strong>Description:</strong></p>
    <h5><%= @sale.description.capitalize %>
  </li>

  <li class="list-group-item">
    <p class="col-sm-2 col-xs-12" style="text-align: right"><strong>Person:</strong></p>
    <h5><%= @sale.person.name %></h5>
  </li>

  <li class="list-group-item">
    <p class="col-sm-2 col-xs-12" style="text-align: right"><strong>Date:</strong></p>
    <h5><%= @sale.date.strftime("%d/%m/%Y")  %></h5>
  </li>
  <li class="list-group-item">
    <p class="col-sm-2 col-xs-12" style="text-align: right"><strong>Status Payment:</strong></p>
    <% porPagar = Quote.where(sale_id:  @sale.id, is_paid: false).order(:number) %>
    <% if porPagar.size > 0 %>
        <h5><td> Quote for pay: <%= porPagar.to_a.at(0).number < 10? '0' + porPagar.to_a.at(0).number.to_s : porPagar.to_a.at(0).number %>/<%= porPagar.to_a.at(0).total < 10? '0' + porPagar.to_a.at(0).total.to_s : porPagar.to_a.at(0).total %> </td></h5>
    <% else %>
        <h5><td> Paid </td></h5>
    <% end %>
  </li>
</ul>

<div class="col-sm-2 col-xs-12"><%= link_to 'Back', sales_path, :class => 'btn btn-default btn-block' %></div>

<div class="col-sm-2 col-xs-12"><%= link_to 'View Quotes', quotes_sale_path(@sale), :class => 'btn btn-info btn-block' %></div>

<div class="col-sm-2 col-xs-12"><%= link_to 'Edit', edit_sale_path(@sale), :class => 'btn btn-primary btn-block' %></div>